import { ReactNode } from "react"

// Third-party dependencies
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"

// Current project dependencies
import "../styles/globals.css"

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Home | JsMarenco",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
